project:
  type: website

website:
  title: "{nik}"
  description: "Nik's personal blog."
  search: false
  navbar:
    right:
      - text: blog
        href: posts
      - icon: github
        href: https://github.com/nikdata
      - icon: linkedin
        href: https://linkedin.com/in/nikagarwal
      - icon: mastodon
        href: https://fosstodon.org/@nikdata
      - icon: reddit
        href: https://www.reddit.com/user/cmdrmac/
      - text: "{{< iconify fa6-brands bluesky >}}"
        href: https://bsky.app/profile/nikhilagarwal.bsky.social
      - icon: strava
        href: https://www.strava.com/athletes/8185543
    background: '#000000'
  page-footer: 
    center:
      - text: © 2018 - 2024 | Nik Agarwal
    border: true
format:
  html:
    theme: cyborg
    css: styles.css



