project:
  type: website

website:
  title: "{nik}"
  page-navigation: false
  navbar:
    right:
      - href: index.qmd
        text: hello
      - href: posts.qmd
        text: blog
      - icon: github
        href: https://github.com/nikdata
      - icon: mastodon
        href: https://fosstodon.org/@nikagarwal
  page-footer:
    center: 
      - "Copyright 2018 - 2022, Nikhil Agarwal"
    right:
      - icon: github
        href: https://github.com/nikdata
      - icon: mastodon
        href: https://fosstodon.org/@nikagarwal

format:
  html:
    theme: slate
    css: styles.css
    mainfont: Quicksand