---
title: My Take on Cycling Training
description: "How I approached my training to to get better at cycling and actually enjoy it"
date: "2024-11-21"
draft: true
toc: true
toc-depth: 4
toc-location: left
code-line-numbers: false
---

## It all started with a new bike

About 2.5 years ago (summer of 2022 to be more precise), I purchased a [2022 BMC Roadmachine Two](https://us.bmc-switzerland.com/collections/bike-archive-road/products/roadmachine-two-bikes-bmc-22-10605-002?_pos=15&_fid=b81251584&_ss=c). At the time, it was a very expensive purchase and over the last 2 years, I've upgraded many of the components. Since this was the most expensive bike I ever bought in my life, I told myself that I'm going to get better at cycling. Great! Now how would I go about doing that?

## Hire a Coach?

Like many sports, I could work with a coach. I looked up cycling coaches (online and local ones) and I was overwhelmed. First off, hiring a coach is not cheap. Having a coach is a true commitment and a very costly endeavor if you don't maximize the benefits the coach offers you. And coaches are not your parents; their job is to help you succeed. Ultimately, you - as the athlete - have to put in the work. The coaches that I found were charging anywhere from $250 to well over $1000 per month.

I knew I wasn't going to train for a race or a cycling event. So I scratched this off my list.

## But I learned something

Every coach started off with one question that really got me thinking: "what's your goal?"

When I first read that question (or variations of it), I didn't really think about it. My answer would always be "I want to ride my bike fast!" But I didn't take the time to think about my own goal. What did I really want to do? What about cycling excites me? 

## What did I really want?

When I got my bike, I would ride as much as I could. I quickly realized that I was pretty tired out after riding for just 10-15 miles. Sure, I wasn't fit - that's why I needed to get better. But I was riding my bike frequently, why wasn't I getting any better? I also learned that there is a technical term for being tired: [bonking](https://www.trainerroad.com/blog/what-is-bonking-causes-dangers-and-prevention/#:~:text=Bonking%20is%20a%20dreaded%20experience,it%20is%20to%20recover%20from.).

**What I wanted was to be able to ride for 2 - 3 hours without bonking**. I wanted to have energy after my bike ride to do household work, spend time with my family, and feel good. 

And this changed how I approached my bike rides and changed how I train for my bike rides. The key word that I focused in on was **endurance**. Endurance is what I needed to work on, develop, and strengthen if I wanted to cycle for hours and having enough energy (or fuel in the tank) after my ride.

## Chase the goal

Now that I knew what I wanted to achieve, I started to look for cycling workout plans. Many of them were either 4 weeks or 8 weeks long. Some of these workouts were labeled as Base or Build. And that confused me! I don't need a *base*, I need to **build** my endurance - so why would I do a Base workout?

It's here that I learned about the different cycling training phases: Base, Build, Specialty.

I'll try to summarize them:

- Base: this phase is all about 'training' your body and mind to adjust to the goal. It's about getting your body stronger and ready for more intense work down the road.
- Build: this phase is all about being better. It builds on the foundations and there are more "stretch" goals.
- Specialty: this phase is honing certain areas to perfection (or as perfect as you can be).

## Strong Foundations

I've been training for well over a year now and I can confidently say that Base phase training is my favorite and the most important. It's in this phase where I enjoy riding my bike at any time. It's all about building the strength, the mental focus, and endurance to ride my bike. It's also the best phase to try out new forms/positions, equipment, etc. More importantly, this phase is where you can really see a difference.

I've done Build phase workouts and they are intense! Build phase is what makes you better, fitter, and stronger. But if you don't have a solid Base foundation, the Build workouts are tough and not very fun. 


