---
title: "What Bike Should You Buy"
date: "2024-06-19"
draft: true
img: road-cycle.jpg
categories:
    - cycling
---

![Photo by <a href="https://unsplash.com/@jackdelulio?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Jack Delulio</a> on <a href="https://unsplash.com/photos/man-in-black-t-shirt-riding-bicycle-on-road-during-daytime-sHhh963Selk?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  ](road-cycle.jpg){align="center" width=70% fig-align="center" fig-alt="A man riding a bicycle on the road."}

When it comes to buying a bicycle, the decision can be overwhelming or it can be super easy! You can easily drive over to your local Wal-Mart and find some really cool bikes for under US$500. How do you know what kind of bike should you buy? Is the decision driven primarily by price? You can also find bikes at garage sales, Facebook Marketplace, OfferUp, and more. So, are used bikes worth it?

## The Three Tenets

I bought a very nice (i.e., expensive) road bike in the summer of 2022 and I arrived at the decision by looking at three different things:

- budget
- goals
- commitment

Each of these three "tenets" - as I refer to them - are inter-related. At first glance, a budget may seem the most important factor; it certainly can be! However, the other tenets can also help 'adjust' the budget.

### Budget

Let's start with the elephant in the room. Two of the most common things I've heard are along the lines of "if you can't afford a nice bike, then save up!" or "if you can't afford the bike, then buy used". Both of these sayings have some merit.

The smart decision - I think - is to **know how much you can comfortably spend**. Bicycles can be had from $200 to well over $15,000! That's a wide range. However, if you are new cycling or are starting to get serious, I think you'll find that it'll be difficult for you to tell the difference between a $1000 bike and a $7000 bike.

Once you have a budget in mind, I don't recommend changing it.

### Goals

If you had a bike, what goals would you want to achieve. For example, if you want to ride 100 miles (a century) in one go, almost any bike will work! Furthermore, it's not the bike that will be your limiting factor nor your budget. More than likely, you won't have the fitness/training necessary to complete a century ride in one go safely, completely, and having fun doing it. In a way, the goal here would be to get fit enough. And that will require more than just a bike.

### Commitment

In my opinion, this is the most important tenet! If you're not committed, spending any money is a waste of money. When I was thinking about buying a new bike, I made the following commitments:

- I will learn how to maintain my bike so I don't have to visit any bike shop
- I will buy the tools necessary so that I can easily maintain my own bike
- I will take the time to understand how to train to ride my bike more effectively
- I will take cycling seriously and treat it as a responsibility
  - This means I will adjust my life to ensure that I achieve my cycling goals

These sound easy to make and follow, but these are not easy commitments. 